### ISSUE TITLE
Doesn't work with now-removed ModuleDefinition.php

### ISSUE THREAD

**Issue by siwilkins** [simplesamlphp/simplesamlphp-module-modinfo#1]
Hi there,

I'm getting the following error:

```
PHP Fatal error:  Class 'sspmod_core_ModuleDefinition' not found in /var/www/simplesamlphp/releases/20150611093838/modules/modinfo/www/index.php on line 12
```

I'm guessing it relates to [this commit](https://github.com/simplesamlphp/simplesamlphp/commit/c63267615a13dc04d2ea1374bbbdf823f8b9bf1e)

**Comment by jaimeperez** [comment]
Hi @siwilkins,

Thanks a lot for your bug report! You are absolutely right, we removed that class while this module is still using it. However, I see actually no value on it, since it's used only to parse a `definition.json` file in the root dir of every module that defines specific parameters of a module. That feature is not documented, and I'm completely unable to even find an example of such a file, so I would just keep the class deleted and edit `index.php` so that it no longer references to it.

In the end, since we switched to composer, module management is delegated to it. If we find it interesting, we could either try to use composer files to gather this information, or even add support for those modules hosted in github, so that the information can be retrieved from here using the API.
